apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-exec-read-logs
rules:
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/log
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/files
    verbs:
      - create
      


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-read-logs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-exec-read-logs
subjects:
  - kind: ServiceAccount
    name: pod-exec-read-logs-sa
    namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-exec-read-logs-sa
